### ISSUE TITLE
dartdoc crashes on yak_utils

### ISSUE THREAD

**Issue by iapicca** [iapicca/yak_packages#157]
```
exitCode: 255
stdout: [2022-07-15T13:49:21.116020] Starting...
Documenting yak_utils...
Initialized dartdoc with 58 libraries
Generating docs for library yak_utils from package:yak_utils/yak_utils.dart...

stderr:   warning: yak_utils has no library level documentation comments
    from yak_utils: (file:///tmp/pub-dartlang-dartdocCSIRKL/pkg/lib/yak_utils.dart:1:9)
Unhandled exception:
Bad state: typedef NullaryAsync<out T> = Future<T> Function() (TypeAliasElementImpl) cannot have parameters
#0      ModelElement.parameters.<anonymous closure> (package:dartdoc/src/model/model_element.dart:856:7)
#1      ModelElement.parameters (package:dartdoc/src/model/model_element.dart:886:4)
#2      ModelElement.parameters (package:dartdoc/src/model/model_element.dart)
#3      FunctionTypedef.referenceChildren (package:dartdoc/src/model/typedef.dart:141:31)
#4      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:115:38)
#5      _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:224:31)
#6      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:265:16)
#7      _makeLinkNode (package:dartdoc/src/markdown_processor.dart:232:16)
#8      new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:339:14)
#9      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1058:34)
#10     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1086:12)
#11     LinkSyntax.close (package:markdown/src/inline_parser.dart:983:14)
#12     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:150:29)
#13     InlineParser.parse (package:markdown/src/inline_parser.dart:106:9)
#14     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:382:67)
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:387:9)
#16     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:372:5)
#17     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:58:21)
#18     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:37:23)
#19     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:31:7)
#20     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:805:50)
#21     __deduplicated_lib_templates_html__typedef_html_partial_type_2 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:3578:25)
#22     _deduplicated_lib_templates_html__typedef_html (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:3504:18)
#23     _renderLibrary_partial_typedef_10 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:2676:5)
#24     renderLibrary (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:1153:20)
#25     HtmlAotTemplates.renderLibrary (package:dartdoc/src/generator/templates.dart:157:30)
#26     DartdocGeneratorBackend.generateLibrary (package:dartdoc/src/generator/dartdoc_generator_backend.dart:192:29)
#27     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:72:27)
#28     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:23:11)
#29     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:181:21)
<asynchronous suspension>
#30     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:223:24)
<asynchronous suspension>
#31     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:32:19)
<asynchronous suspension>

```

**Comment by iapicca** [comment]
it's [dart's fault](https://github.com/dart-lang/dartdoc/issues/3132)

**Comment by iapicca** [comment]
should try again https://github.com/dart-lang/dartdoc/pull/3193
