### ISSUE TITLE
[yak_utils] pub.dev keeps failing to generate docs

### ISSUE THREAD

**Issue by iapicca** [iapicca/yak_packages#196]
```console
exitCode: 255
stdout: [2022-10-13T15:26:09.496962] Starting...
Documenting yak_utils...
Initialized dartdoc with 76 libraries
Generating docs for library yak_utils from package:yak_utils/yak_utils.dart...

stderr:   warning: yak_utils has no library level documentation comments
    from yak_utils: (file:///tmp/pub-dartlang-dartdocRRFKIS/pkg/lib/yak_utils.dart:1:9)
Unhandled exception:
Null check operator used on a null value
#0      ModelElement.parameters.<anonymous closure> (package:dartdoc/src/model/m[...]
#1      ModelElement.parameters (package:dartdoc/src/model/model_element.dart:895:4)
#2      ModelElement.parameters (package:dartdoc/src/model/model_element.dart)
#3      FunctionTypedef.referenceChildren (package:dartdoc/src/model/typedef.dart:133:31)
#4      CommentReferable.referenceBy (package:dartdoc/src/model/comment_referabl[...]
#5      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:226:30)
#6      getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:238:16)
#7      MarkdownDocument._makeLinkNode (package:dartdoc/src/markdown_processor.d[...]
#8      new MarkdownDocument.withElementLinkResolver.<anonymous closure> (packag[...]
#9      LinkSyntax._resolveReferenceLink (package:markdown/src/inline_syntaxes/l[...]
#10     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_syntaxes[...]
#11     LinkSyntax.close (package:markdown/src/inline_syntaxes/link_syntax.dart:40:14)
#12     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:158:31)
#13     InlineParser.parse (package:markdown/src/inline_parser.dart:114:9)
#14     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_proce[...]
#15     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_proce[...]
#16     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_process[...]
#17     Documentation._parseDocumentation (package:dartdoc/src/model/documentati[...]
#18     Documentation._renderDocumentation (package:dartdoc/src/model/documentat[...]
#19     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:54:5)
#20     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:816:49)
#21     _deduplicated_lib_templates_html__typedef_html (package:dartdoc/src/gene[...]
#22     _renderLibrary_partial_typedef_10 (package:dartdoc/src/generator/templat[...]
#23     renderLibrary (package:dartdoc/src/generator/templates.aot_renderers_for[...]
#24     HtmlAotTemplates.renderLibrary (package:dartdoc/src/generator/templates.[...]
#25     GeneratorBackendBase.generateLibrary (package:dartdoc/src/generator/gene[...]
#26     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator[...]
#27     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_fron[...]
#28     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:178:21)
<asynchronous suspension>
#29     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:220:24)
<asynchronous suspension>
#30     main (file:///project/pkg/pub_dartdoc/bin/pub_dartdoc.dart:32:19)
<asynchronous suspension>
```

see 
https://github.com/iapicca/yak_packages/issues/157
https://github.com/dart-lang/dartdoc/pull/3193
https://github.com/dart-lang/dartdoc/issues/3132

**Comment by iapicca** [comment]
fixed in yak_utils 2.0.0
